name: Build (Manual)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - name: Install dependencies
      run: npm ci
    - name: Fetch
      run: npm run fetch
    - name: Compile
      run: npm run webpack:compile
    - name: Package Windows
      if: runner.os == 'Windows'
      run: node release-automation/build.js --windows --windows-legacy --microsoft-store
    - name: Package macOS
      if: runner.os == 'macOS'
      run: node release-automation/build.js --mac
    - name: Package Linux
      if: runner.os == 'Linux'
      run: node release-automation/build.js --debian --tarball --appimage
      env:
        USE_HARD_LINKS: false
