name: Release

on:
  push:
    tags:
    - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: npm
    - name: Install dependencies
      run: npm ci
    - name: Fetch
      run: npm run fetch

    - name: Compile
      run: npm run webpack:prod

    - name: Package Windows
      if: runner.os == 'Windows'
      run: |
        node release-automation/build.js --windows --x64 --production
        node release-automation/build.js --windows --ia32 --production
        node release-automation/build.js --windows --arm64 --production
        node release-automation/build.js --windows-legacy --x64 --production
        node release-automation/build.js --microsoft-store --x64 --production
        node release-automation/build.js --microsoft-store --ia32 --production
        node release-automation/build.js --microsoft-store --arm64 --production
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload Microsoft Store Artifact
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v4
      with:
        name: appx
        path: dist/*.appx

    - name: Package macOS
      if: runner.os == 'macOS'
      run: |
        node release-automation/build.js --mac --universal --production
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        APPLE_ID_USERNAME: ${{ secrets.APPLE_ID_USERNAME }}
        APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
        APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        CSC_LINK: ${{ secrets.CSC_LINK }}

    - name: Package Linux
      if: runner.os == 'Linux'
      run: |
        node release-automation/build.js --debian --x64 --production
        node release-automation/build.js --debian --armv7l --production
        node release-automation/build.js --debian --arm64 --production
        node release-automation/build.js --tarball --x64 --production
        node release-automation/build.js --tarball --armv7l --production
        node release-automation/build.js --tarball --arm64 --production
        node release-automation/build.js --appimage --x64 --production
        node release-automation/build.js --appimage --armv7l --production
        node release-automation/build.js --appimage --arm64 --production
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
